### ISSUE TITLE
Step measure at the beginning

### ISSUE THREAD

**Issue by BrunoAtGit** [nishantjainuk/SimpleWaterfallPBI#1]
I really like the simplicity of thy waterfall chart, but looking for a solution to start with a step measure in the beginning followed by a base measure. Is this something you can consider as an enhancement?

**Comment by alexisechague** [comment]
Thanks for your visualization!!! Same requirement, if it is possible to start with a step, not a total. Thanks!

**Comment by nishantjainuk** [comment]
I have added this feature and the latest version is pending with Microsoft. It should get released in next couple of weeks. Watch out for the latest version, and thanks for your feedback. Please keep them coming
