### ISSUE TITLE
Simple Waterfall outdated version in the PowerBI Market

### ISSUE THREAD

**Issue by LeonDth** [nishantjainuk/SimpleWaterfallPBI#3]
Great PowerBI visual, it really allows to make great custom waterfalls, something the built-in PowerBI waterfall lacks. Sadly, whenever I download the visual from the PowerBI Marketplace, I get version 1.5.0, a version that seems to lack some of functionalities that version 2.0 has. Is it possible to update the visual on the marketplace or to upload the custom visual .pbiviz to the repository?

**Comment by nishantjainuk** [comment]
Hi there

It's great to hear that you find the visual useful.

Version 2.0 went live earlier this week but it can take upto 2 weeks for it to appear in marketplace. I have attached the dev version of it, in case you want to use it now. Make sure you delete it and use the version from the marketplace when it goes live.

Would appreciate if you could leave some feedback on marketplace.

Any questions let me know.


Thanks
Nishant


On 28 Nov 2019 at 10:37, LeonDth <notifications@github.com<mailto:notifications@github.com>> wrote:


Great PowerBI visual, it really allows to make great custom waterfalls, something the built-in PowerBI waterfall lacks. Sadly, whenever I download the visual from the PowerBI Marketplace, I get version 1.5.0, a version that seems to lack some of functionalities that version 2.0 seems to have. Is it possible to update the visual on the marketplace or to upload the custom visual .pbiviz to the repository?

**Comment by LeonDth** [comment]
Great, thanks a lot :D
