### ISSUE TITLE
Simple Waterfal

### ISSUE THREAD

**Issue by mlcade1** [nishantjainuk/SimpleWaterfallPBI#6]
Love your Simple Waterfall Power BI visualization! With the new updates, I believe "Definte Pillars" has disappeared. Can we get it back? Or is there another way to identify total pillars?

thank you!

**Comment by nishantjainuk** [comment]
Hey, sorry couldn't understand what has disappeared. Can you provide more information?


On 4 Dec 2019 at 23:31, mlcade1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Love your Simple Waterfall Power BI visualization! With the new updates, I believe the has disappeared. Can we get it back? Or is there another way to identify total pillars?

thank you!

**Comment by mlcade1** [comment]
My apologies, I went back in and edited the question! "Define Pillars" option is missing from the Format section. I'm on the most up to date Power BI version. 

Thank you for your prompt reply!

**Comment by nishantjainuk** [comment]
How many measures and categories you are using?

Also have you tried to delete and recreate the visual


On 4 Dec 2019 at 23:36, mlcade1 <notifications@github.com<mailto:notifications@github.com>> wrote:


My apologies, I went back in and edited the question! "Define Pillars" option is missing from the Format section. I'm on the most up to date Power BI version.

Thank you for your prompt reply!

**Comment by mlcade1** [comment]
4 measures. 1 is the total, the other 3 match the total of the 4th. Snapshots provided
![Capture](https://user-images.githubusercontent.com/58535146/70191086-475b0980-16bd-11ea-9df8-f247a7358e0b.PNG)
![Capture1](https://user-images.githubusercontent.com/58535146/70191087-475b0980-16bd-11ea-87db-93be40cde2dd.PNG)
![Capture2](https://user-images.githubusercontent.com/58535146/70191088-475b0980-16bd-11ea-8fb0-9d482f63366b.PNG)

**Comment by mlcade1** [comment]
B/(W) I need to indicate as my total.

**Comment by nishantjainuk** [comment]
What is the version of the visual you have?


On 4 Dec 2019 at 23:42, mlcade1 <notifications@github.com<mailto:notifications@github.com>> wrote:


B/(W) I need to indicate as my total.

**Comment by nishantjainuk** [comment]
The version available on the app. Store is 1.5.0 which doesn't have the "Define Pillars" option. It is available from version 2.0.

It takes about 2 weeks for the visual to go live on the market place. If you can't wait until then, below is the link to the 2.0 version of the visual in case you want to use it now. Make sure you delete it and use the version from the marketplace when it goes live.

https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/SimpleWaterfall_dev.2.0.3.pbiviz

Thanks
Nishant
On 4 Dec 2019 at 23:42, mlcade1 <notifications@github.com<mailto:notifications@github.com>> wrote:


B/(W) I need to indicate as my total.

**Comment by mlcade1** [comment]
Version 2.0.2.0 released 7/24/19

**Comment by nishantjainuk** [comment]
That's what you see on market place. But check the version that gets installed by right clicking on the visual image in the visualisation pane. I still get v1.5.0 which means Microsoft haven't made the latest version available.

Check my previous email to get the latest beta version

Thanks
Nishant



On 5 Dec 2019 at 00:05, mlcade1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Version 2.0.2.0 released 7/24/19

**Comment by mlcade1** [comment]
This worked! Thank you! :)
